### ISSUE TITLE
Spotify icon looks bad

### ISSUE THREAD

**Issue by lights0123** [daniruiz/flat-remix#101]
The new Spotify icon looks much worse than it used to:
![Flat](https://user-images.githubusercontent.com/3756309/54483999-13d90600-4834-11e9-8396-ae149d89e2f8.png)
In comparison, this is the actual icon:
![Default](https://user-images.githubusercontent.com/3756309/54484004-1e939b00-4834-11e9-9c4d-4889baf1d311.png)
And how Numix Square shows it:
![Numix](https://user-images.githubusercontent.com/3756309/54484006-25221280-4834-11e9-972d-f765e9d42052.png)

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/54852565-868f2900-4ced-11e9-9f6b-4ae51aa266b5.png)

I don't think it looks bad, it just uses a darker color to fit with Flat Remix's color palette
