### ISSUE TITLE
Sugerencias acerca del tema de íconos 

### ISSUE THREAD

**Issue by gusbemacbe** [daniruiz/flat-remix#102]
Hola @daniruiz !

He charlado con aquel usuario y me gustaría explicar a ti.

Se sugieres que los usuarios de KDE pongan tu tema de íconos en `~/.icons`, eso no funcionará.

**KDE:** `~/.local/share/icons`
**GTK:** `~/.icons`
**Deepin:** `/usr/share/icons`

Se instalas la ultima versión de tu tema de íconos, pero no limpias el cache ni reinicializas, los íconos permanecerán viejos. Cambiar de íconos y actualizar la ultima versión no reiniciará el cache. Eso ocurre más en el KDE.

Creo que deberías hacer fork de algunos archivos de mi tema de íconos [Suru++](/gusbemacbe/suru-plus) – `install.sh`, `Makefile` y `travis.yml` (eso es importante para analizar/verificar se no hay errores en tu tema de íconos) y copiar alguna parte de mi README ("Installation").

**Comment by daniruiz** [comment]
Hey! Gracias! Le echaré un ojo a tus scripts de Suru++, me pueden venir muy bien :smile: 

Tienes razón, se me olvidó especificar la instalación para KDE en ~/.local/share/icons. De todos modos en deepin si que funciona en ~/.icons.
El tema de la cache es también solo en KDE, pero creo que si no has creado la cache no habría problema no? Es decir, el problema sería que tuvieras una cache de iconos antigua, pero si no la creaste no hay problema, los iconos cargarían un poco mas lento eso si.

**Comment by gusbemacbe** [comment]
> El tema de la cache es también solo en KDE, pero creo que si no has creado la cache no habría problema no

En el KDE, todavía habría porque ocurrió muchas veces conmigo. Cuando yo he actualizado las versiones nuevas de los temas de iconos, los iconos todavía permanecieron viejos. Tenía de utilizar el Stacer para limpiar los caches, pero como todavía no funcionó, tenía de ejecutar el comando `gtk-update-icon-cache`, e se todavía no funcionó, tenía de reinicializar. KDE es más bugado que el GTK. Por eso, tienes de explicar a los usuarios de KDE acerca de esos problemas.

**Comment by gusbemacbe** [comment]
Hola @daniruiz !

El forum brasileño ha indicato tu tema de iconos: https://plus.diolinux.com.br/t/apresente-o-seu-desktop-e-mostre-o-quanto-o-linux-e-bonito/153/550?u=gusbemacbe :-)

**Comment by daniruiz** [comment]
@gusbemacbe Gracias por pasarme el link! Que guay :smile: Esta bien saber que a la gente le gustan mis temas.

Cierro esta issue simplemente para tener mas libre el panel de issues :+1:

**Comment by gusbemacbe** [comment]
Pero todavía no has resuelto. Aquí está en tu README:

```Markdown
Move "Flat Remix" folder to ".icons" in your home directory.
```

Eso no funcionará en el KDE. Deberías mejorar el README.

**Comment by daniruiz** [comment]
Ups se me paso :sweat_smile: Ya lo he corregido aquí y también en opendesktop
