### ISSUE TITLE
geary icon need to change

### ISSUE THREAD

**Issue by algent-al** [daniruiz/flat-remix#105]
![geary icon - Flat Remix](https://user-images.githubusercontent.com/46356616/54907389-adb04b00-4ee5-11e9-9e06-c262360b7ee8.png)
I am using Qogir Dark theme.
Geary icon doesn't look well.

**Comment by daniruiz** [comment]
I see it great, whats the issue?

**Comment by algent-al** [comment]
I think is too much white, the lines that forms envelope barely look. I think it needs sharper borders, or diferent color for the inside of the envelope.
