### ISSUE TITLE
Purple variant color theme? 

### ISSUE THREAD

**Issue by koesherbacon** [daniruiz/flat-remix#108]
Hello there. I'd like to know how tough it would be to create a purple variant to go with the existing blue, green, red and yellow varieties already available. Would I be able to edit the `/tools/colorfixer.sh` or `/tools/ColorFolderColorFolderGenerator.sh` in order to produce a purple variant? 

Would it instead be better to just install the default blue manually, and recolor the folders using Inkscape instead? 

If it's the Inkscape idea, how can I then share the purple variant back to you for others to enjoy?

Thanks!
⁓ Ev

**Comment by daniruiz** [comment]
There is already a magenta variant that could work for you:
![folder-magenta](https://user-images.githubusercontent.com/12565871/57178109-3bc80b80-6e6c-11e9-8863-5caf200cb93f.png)
If you wan't to use this folder variant as the main color you can replace the original ones with those with the '*-magenta'  name (or any other color) removing color name. For example rename folder-magenta.svg with just folder.svg...

Anyway if you want another color variant you can modify the script inside `tools/colorFolder/colorFolderGenerator.sh` and change the color values inside `color1_new` and `color2_new`. Then you just need to place a terminal inside  `tools/colorFolder/places` and run `../colorFolderGenerator.sh`

You can also change manually some folder's color installing `folder-color` https://foldercolor.tuxfamily.org/
