### ISSUE TITLE
Update repo for fedora 30

### ISSUE THREAD

**Issue by inzar98** [daniruiz/flat-remix#110]
Hi @daniruiz 

I loved so much your theme but we cant download it from fedora repo for fedora30

If you gonna update it that will be awesome :)

**Comment by josh1dev** [comment]
Try refreshing or updating copr / dnf, working fine for me on Fedora 30.

**Comment by daniruiz** [comment]
I'm using Fedora 30 aswell and it works fine, so I'll asume it's resolved
