### ISSUE TITLE
Some system icons not working on update to Ubuntu 19.04

### ISSUE THREAD

**Issue by ThatFatPat** [daniruiz/flat-remix#111]
![Screenshot from 2019-04-19 10-41-10](https://user-images.githubusercontent.com/29810938/56413475-4a20ff80-6290-11e9-9a99-adcc3bca0054.png)
Terminal, Help, Fonts and possibly others break after update.

**Comment by ThatFatPat** [comment]
After some digging around it turns out GNOME 3.32 decided to change some icon names. I am currently trying to get the theme again by creating symlinks in the scalable folder to the original svg files to no avail. Maybe I am doing something wrong?

**Comment by daniruiz** [comment]
Is it fixed now, with latest ppa update? Bear in mind that some apps from ubuntu come as snap preinstalled so the icons are fixed

**Comment by ThatFatPat** [comment]
Can confirm the latest update does fix it. Although the Flat Remix and Flat Remix Dark icon themes disappeard, instead leaving only the options with color. That's strange...

**Comment by daniruiz** [comment]
Yep, that's normal, as I've renamed the default themes to Blue, so that they match gtk theme variants
