### ISSUE TITLE
[Suggestion] Recolored the Blender's icon

### ISSUE THREAD

**Issue by RavengamerSpace** [daniruiz/flat-remix#113]
I personally found the Blender icon too red instead of the orange of the original icon.
So I change the color and here is what it looks:
</br>
![blender](https://images.weserv.nl/?url=https://user-images.githubusercontent.com/28545669/56851853-18eda280-6914-11e9-9fd1-039447af6025.png&w=128&h=128)
</br>
So, what do you think of it ?
</br>
PS: You can download the file [here](https://github.com/daniruiz/flat-remix/files/3124054/blender_new_icon.zip)

**Comment by daniruiz** [comment]
Sorry, but I still prefer the current one :sweat_smile:
