### ISSUE TITLE
Two packages in the AUR

### ISSUE THREAD

**Issue by astier** [daniruiz/flat-remix#114]
There are two packages in the AUR:

- flat-remix
- flat-remix-git

On your site you refer to flat-remix however, flat-remix-git seems to be the mostly used package based on the votes and popularity. What is the difference between the two packages and which one should be used on Arch Linux?

**Comment by astier** [comment]
Also what is the difference to flat-remix-gtk?

**Comment by daniruiz** [comment]
`flat-remix` was supposed to replace flat-remix-git but on aur they've rejected my "merge request". The difference is that flat-remix-git downloads the last commit and installs it, so you get the latest updates but they could be unfinished or just not even tested. By the other hand `flat-remix` (without '-git') relies on a more stable update model, as it download the package from git releases https://github.com/daniruiz/flat-remix/releases

`flat-remix-gtk` (https://github.com/daniruiz/flat-remix-gtk) is a theme for gtk applications. Here is an example of nautilus, gnome's default file manager:
![image](https://user-images.githubusercontent.com/12565871/57178051-47ff9900-6e6b-11e9-889d-fcbacfaa14bf.png)

(Not asked for this, but it may also be helpful)
`flat-remix-gnome` (https://github.com/daniruiz/flat-remix-gnome) is a gnome-shell theme, not for windows decorations but for panels and desktop elements in general:
![image](https://user-images.githubusercontent.com/12565871/57178070-ae84b700-6e6b-11e9-95ac-e82123dc19fa.png)

**Comment by astier** [comment]
Thank you very much for your reply.

1. If `flat-remix-gtk` is for gtk-applications does it mean that `flat-remix` is for qt-applications or is it also supposed to be used for gtk-applications?

2. Should `flat-remix-gnome` then be used in combination with one of the above packages? Does it make sense to be used for cinnamon and other DEs or is it only for gnome?
