### ISSUE TITLE
No window border

### ISSUE THREAD

**Issue by BiglinuxLover** [daniruiz/flat-remix#116]
Hello, i ma using your gtk theme on xfce and it's working great exept i can't find the window border on xfce.
I only works when using metacity wm and i am using compton for tearing problems.
Is there any fix ?
Thanks a lot for your time

**Comment by daniruiz** [comment]
At the moment the theme doesn't support xfce window theming but, good news! Next week I'll release a new version that will provide xfwm4 window decorations ;)

Anyway I close this issue as this repo is for the icon theme. What you are looking for is the gtk theme https://github.com/daniruiz/flat-remix-gtk
There are already some opened issues about this topic
