### ISSUE TITLE
AUR package flat-remix installation via yay aborts

### ISSUE THREAD

**Issue by astier** [daniruiz/flat-remix#117]
Recently downloading and installing the package `flat-remix` via yay aborts with the following message:

> ERROR: Failure while downloading https://github.com/daniruiz/flat-remix/archive/20190525.tar.gz

I didn't try it with other aur-managers. The package `flat-remix-git` works however.

**Comment by astier** [comment]
Right above the following message is also show:

> curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

**Comment by daniruiz** [comment]
It's working perfectly for my. Try to clean yay cache `yay -Sc` and then reinstalling

**Comment by astier** [comment]
Thank you. This made it work.
