### ISSUE TITLE
Update Visual Studio Code logo

### ISSUE THREAD

**Issue by arpit73** [daniruiz/flat-remix#119]
Visual Studio Code team has updated the logo. I think the new one will look good and fit in well with the current icon set without many changes. 
https://code.visualstudio.com/updates/v1_35#_updated-visual-studio-code-icon

**Comment by KushagraKarira** [comment]
Here you go,
Now someone add these to the repo.
[ Stable ](https://github.com/KushagraKarira/GraphicResource/blob/master/Icons/logo-stable.svg)
[ Insiders ](https://github.com/KushagraKarira/GraphicResource/blob/master/Icons/logo-insiders.svg)
