### ISSUE TITLE
Please add this theme to flathub

### ISSUE THREAD

**Issue by serovar** [daniruiz/flat-remix#122]
Unfortunately flatpak applications can't use the system GTK theme if there is not the same theme, with the same name, installed as flatpak. Could it be possible to add flat-remix-gtk to the flathub repo, please?

**Comment by KushagraKarira** [comment]
Here you go,
Now someone add these to the repo.
[ Stable ](https://github.com/KushagraKarira/GraphicResource/blob/master/Icons/logo-stable.svg)
[ Insiders ](https://github.com/KushagraKarira/GraphicResource/blob/master/Icons/logo-insiders.svg)

**Comment by daniruiz** [comment]
Duplicated https://github.com/daniruiz/flat-remix-gtk/issues/28
