### ISSUE TITLE
Radios symbolic icon size issue

### ISSUE THREAD

**Issue by Dvlnst** [daniruiz/flat-remix#123]
Hi,

Radios symbolic icon size is diferent than the other ones. See a screenshot of lollypop sidebar (Works well with default icons theme):

![Screenshot from 2019-08-01 15-59-50](https://user-images.githubusercontent.com/36289254/62299749-d3da8e80-b475-11e9-81ba-7ccc744a62e5.png)

Kind regards.

**Comment by daniruiz** [comment]
This issue is old, so I'm closing it. Please, try the new updates and let me know if the bug persists
