### ISSUE TITLE
work online/offline button doesn't scale in Evolution

### ISSUE THREAD

**Issue by chasenpse** [daniruiz/flat-remix#126]
Great icons & themes, however I am having an issue in Evolution. For context I believe [this](https://github.com/daniruiz/flat-remix/issues/25) issue is related.

The work online/offline button doesn't appear to scale down and displays [very large](https://imgur.com/a/KH9u6Cz). This is on Gnome 3.28.2 on Ubuntu 18.04.

**Comment by Project-FreeMind** [comment]
I have the same problem under Manjaro KDE.

![flatremix_error](https://user-images.githubusercontent.com/54583902/63772108-b95ece00-c8d8-11e9-9d1b-1e7f444d7a91.png)

**Comment by daniruiz** [comment]
What a weird issue... I don't know why evolution is the only app that gets an icon and uses it with the default size, and it only does it with the online/offline icon, the rest scale perfectly. Anyway y downscale them to 32px and now it works perfectly :wink:
