### ISSUE TITLE
ElectronMail tray icon issue

### ISSUE THREAD

**Issue by Dvlnst** [daniruiz/flat-remix#128]
Hi,

[ElectronMail](https://github.com/vladimiry/ElectronMail) tray icon is overwrite by electron default icon. Could you fix it?

Kind regards.

**Comment by aquaductape** [comment]
It's because they removed it. So far I was only able to find the tray icon of it `/Flat-Remix-Blue/panel/electron-mail-tray.svg`

**Comment by daniruiz** [comment]
This issue is old, so I'm closing it. Please, try the new updates and let me know if the bug persists
