### ISSUE TITLE
[Question] Is there a way to bring back old Veracrypt icon?

### ISSUE THREAD

**Issue by Dvlnst** [daniruiz/flat-remix#129]
Hi,

I don't like this new icon, It doesn't fit with other ones. I would just ignore it, but I have Veracrypt pinned on my dash and I cannot do it.

Thanks for the awsome job.

Kind regards.

**Comment by daniruiz** [comment]
Hi,in another commit I've modified a bit some colors. You can download the old icon from old commits. How can I improve the icon? Any suggestions

**Comment by Dvlnst** [comment]
I think the key is the background. Take a look of my dash to dock icons:

![Screenshot from 2019-09-01 18-51-23](https://user-images.githubusercontent.com/36289254/64079605-d553dc80-cce9-11e9-9590-62e179b59dea.png)

Veracrypt icon breaks harmony with the other ones. But I have to say that I'm getting used to it over time, so you can close this issue.

Thanks for the work.

Kind regards.
