### ISSUE TITLE
Gimp shows native icon

### ISSUE THREAD

**Issue by sexling** [daniruiz/flat-remix#130]
I have Icons set to Flat-Remix-Blue and so far everything is replaced expect gimp. I downloaded gimp from Ubuntu Software Center. Its version 2.10.12 and I have Ubuntu 18.04.3 LTS.

**Comment by daniruiz** [comment]
Maybe ubuntu installed the snap version. Try installing it from the terminal `sudo apt install gimp`

**Comment by sexling** [comment]
Oh I see, so snap versions are not supported. That makes sense since I installed dconf-editor from ubuntu software center, but since it wasn't installed as the snap version, it's icon got updated. Removed gimp and installed the package from terminal and icon was updated.
