### ISSUE TITLE
icon Request

### ISSUE THREAD

**Issue by ALipAkrohk** [daniruiz/flat-remix#135]
XiaomiTool : [WebSite](https://www.xiaomitool.com/) | [Wikipedia](https://en.wikipedia.org/wiki/Xiaomi){XiaomiCompany}
AppIconName: xiaomitool
AppIcon : 
![Screenshot_20191025_131314](https://user-images.githubusercontent.com/27810360/67561378-93fc0e00-f729-11e9-919a-7ecc0c321d32.png)
![Screenshot_2019-10-25 XiaoMiTool V2 - Modding of Xiaomi devices made easy for everyone](https://user-images.githubusercontent.com/27810360/67561413-a6764780-f729-11e9-962a-049c9fae48a9.png)
////////////////////////////////////////////////////
Draw.io : [WebSite](https://www.draw.io/) | [About](https://about.draw.io/)
AppIconName: drawio
AppIcon: 
![Screenshot_2019-10-25 draw io - Diagrams For Everyone, Everywhere](https://user-images.githubusercontent.com/27810360/67562108-fbff2400-f72a-11e9-9ddc-a210c413ce8e.png)
////////////////////////////////////////////////////
Persepolis is a Download Manager : [WebSite](https://persepolisdm.github.io/) | [WikiPedia](https://en.wikipedia.org/wiki/Persepolis){the ancient city}
AppIconName: com.github.persepolisdm.persepolis
AppIcon: 
![Screenshot_2019-10-25 persepolisdm persepolis](https://user-images.githubusercontent.com/27810360/67562902-7aa89100-f72c-11e9-80e8-a7fd01ae09b0.png)
////////////////////////////////////////////////////
JetBrainsApps:  [WebSite](https://www.jetbrains.com/) | [WikiPedia](https://en.wikipedia.org/wiki/JetBrains)

**Comment by daniruiz** [comment]
Moved to https://github.com/daniruiz/flat-remix/issues/152
