### ISSUE TITLE
QGIS icon

### ISSUE THREAD

**Issue by mebloscian** [daniruiz/flat-remix#136]
Hello :)

Replacing QGIS icon with Gmaps one one is kinda missleading, it's different kind of software, and the original QGIS logo is already fitting in. Link to the original:
https://upload.wikimedia.org/wikipedia/commons/9/91/QGIS_logo_new.svg

**Comment by daniruiz** [comment]
Fixed! sorry for the delay
![qgis](https://user-images.githubusercontent.com/12565871/85441760-c21f3f80-b58f-11ea-9143-d59a46aa92c2.png)
