### ISSUE TITLE
Weird terminal icon display

### ISSUE THREAD

**Issue by stat1x** [daniruiz/flat-remix#139]
Hi,

When selecting flat-remix icon set, my terminal icon looks weird (see screen shot below)

![image](https://user-images.githubusercontent.com/11523234/73430941-81ecc580-433f-11ea-992b-7d19cf609389.png)

Here are some information about the terminal I am using :

![image](https://user-images.githubusercontent.com/11523234/73431186-1e16cc80-4340-11ea-9a6e-ac736fb07e89.png)

**Comment by daniruiz** [comment]
That is an issue of the terminal, it was fixed in a newer version
