### ISSUE TITLE
Dani, el icono para el atom "molaba" más el otro

### ISSUE THREAD

**Issue by vmvwebworks** [daniruiz/flat-remix#140]
Al actualizar los iconos, se ha puesto de nuevo el que parece nativo, con volumén y no queda tan chachi.

**Comment by daniruiz** [comment]
Este es el que ves ahora?

![atom](https://user-images.githubusercontent.com/12565871/73671021-83551f80-46aa-11ea-9930-95bc01bed800.png)

**Comment by daniruiz** [comment]
El que había antes era este 
![atom](https://user-images.githubusercontent.com/12565871/73671238-dc24b800-46aa-11ea-9ed9-dc116c1a6980.png)

A mi me sigue molando mas el de ahora. Pero bueno, siempre te puedes bajar esta imagen y reemplazar el icono

**Comment by vmvwebworks** [comment]
si, es lo que he hecho, me molaba más el antiguo pero bueno, eres tú el maestro aquí :3

**Comment by daniruiz** [comment]
Es que ya no está de moda iconos tan planos, si te fijas ahora son planos pero con sombras y degradados. Mira el nuevo icono de firefox por ejemplo:
![image](https://user-images.githubusercontent.com/12565871/73695208-f1fda180-46d9-11ea-81f8-408da7bea9f4.png)
