### ISSUE TITLE
Add some missing icons uncovered by gnome-shell 3.36.1

### ISSUE THREAD

**Issue by terencode** [daniruiz/flat-remix#142]
When updating to gnome-shell 3.36.1 from 3.36.0, the following commit was included:

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1127/diffs?commit_id=c89d6a633aa431adda8080665e38d957146c5357

This made  gnome-shell show the "image-missing" icon when it cannot find the given one.

This makes one of my menu a bit ugly because the extension was relying on using a 'blank' icon to get the spacing right probably :
![image](https://user-images.githubusercontent.com/12665563/78087696-2b911700-73c2-11ea-8607-0c9d5a66db3c.png)

It seems this extension (https://github.com/kgshank/gse-sound-output-device-chooser) is the only one I could find that used this 'blank' icon workaround so unless you know this icon is somehow standard, the fix shouldn't come from you. I opened an issue about it here: https://github.com/kgshank/gse-sound-output-device-chooser/issues/95

However, I found the following are used by appindicators (https://github.com/ubuntu/gnome-shell-extension-appindicator) and seems to be rather common:

- 'application_exit'
- 'view_refresh'
- 'view_fullscreen'
- 'view_restore'

**Comment by terencode** [comment]
It's probably a matter of symlinks.

**Comment by daniruiz** [comment]
Is this still happening? I'm not able to reproduce it

**Comment by terencode** [comment]
This seems fixed indeed.
