### ISSUE TITLE
Gnome Poweroff Window Selection Differentiation 

### ISSUE THREAD

**Issue by Nesaijn** [daniruiz/flat-remix#145]
In the Gnome poweroff selection, there is no way to see what option is currently selected. Moving the selection with the cursor or hovering the mouse over the options. They always look the same. 

![Screenshot from 2020-04-19 14-26-51](https://user-images.githubusercontent.com/25134837/79688000-5b0da380-824b-11ea-8a7d-2162111fa3a1.png)

Shell Theme: Flat-Remix-Darkest-fullPanel

**Comment by daniruiz** [comment]
Not an issue
