### ISSUE TITLE
Icon Request : Inkscape Global Settings

### ISSUE THREAD

**Issue by KushagraKarira** [daniruiz/flat-remix#146]

**Comment by KushagraKarira** [comment]
![Screenshot from 2020-05-02 13-09-04](https://user-images.githubusercontent.com/36698785/80858387-a88c0680-8c76-11ea-8dee-f8dc4cc7b85e.png)

The image has been attached for which icon needs to be made.

**Comment by KushagraKarira** [comment]
Gnome-shell : 3.36.1
Distro : Debian testing
Inkscape : 0.92.5

**Comment by daniruiz** [comment]
Fixed with inkscape 1.0
![image](https://user-images.githubusercontent.com/12565871/81218729-f5593f80-8fde-11ea-9f48-66fe90bf2bac.png)
