### ISSUE TITLE
Trash icon doesn't look good on light backgrounds

### ISSUE THREAD

**Issue by philipzae** [daniruiz/flat-remix#153]
I tried Flat-Remix-Blue, Blue-Dark, and Blue-Light and the trash can icon wasn't easy to see on light backgrounds, like the Greybird theme that is the default in Xubuntu.

![image](https://user-images.githubusercontent.com/4412114/85880993-f6903700-b7ed-11ea-9e27-f390d09ccde4.png)

**Comment by daniruiz** [comment]
Well, it doesn't look good on grey backgrounds, but flat-remix themes are white, so the trash icon is perfectly visible there.
