### ISSUE TITLE
24px open folder missing

### ISSUE THREAD

**Issue by philipzae** [daniruiz/flat-remix#154]
16px and 32px icons are present, but 24px icon is missing.
![image](https://user-images.githubusercontent.com/4412114/85881322-7a4a2380-b7ee-11ea-83dc-6d498e1ecbdd.png)

**Comment by daniruiz** [comment]
Which program is that?

**Comment by philipzae** [comment]
Thunar, xfce's file manager.

**Comment by daniruiz** [comment]
Sorry but you're using an old version of thunar based on GTK2. Unfortunately, I'm not able to support old DE's as much as I'd like to, but it does work on newer versions of Thunar, for example on Xfce 4.14
![image](https://user-images.githubusercontent.com/12565871/95576662-1b24bd80-0a31-11eb-9121-52b111aaec7e.png)

**Comment by philipzae** [comment]
I am using thunar on Xubuntu 20.04 which is Xfce 4.14 with gtk3.

**Comment by philipzae** [comment]
You need to set tree pane icons to 24px to see the issue.

![image](https://user-images.githubusercontent.com/4412114/95580137-e112e600-0a47-11eb-8c96-f475035467d0.png)

**Comment by daniruiz** [comment]
Ups! okay, I'll check it again

**Comment by philipzae** [comment]
Any chance to check it?

**Comment by daniruiz** [comment]
I've checked all sizes and it does work with Xfce 4.16
