### ISSUE TITLE
Variant of theme without third-party app icons.

### ISSUE THREAD

**Issue by a2leexx** [daniruiz/flat-remix#155]
Hi!

I use Flat-Remix theme in GNOME, it's a very beautiful theme. You are doing a great job!

Can you release version of this icon theme that doesn't override third-party software icons? The icons are awesome but I prefer that applications like GIMP or Thunderbird have native icons in the "Applications" screen.

**Comment by daniruiz** [comment]
Sorry but I can't create that many variants
