### ISSUE TITLE
shockwave flash mimetype icon not showing

### ISSUE THREAD

**Issue by XxArashkxX** [daniruiz/flat-remix#157]
Hello,
I've noticed that the icons for shockwave flash files show as the "video-x-generic" icons while there are svg files in the icon theme that are specifically made for flash files. I checked the /usr/share/mime/application/vnd.adobe.flash.movie.xml files and it says type="application/vnd.adobe.flash.movie". So can you please make a flash icon with that name in the mimetypes? I've also realised the same is for rar archives. they show as "package-x-generic" and the xml file for that one says type="rar.vnd".

**Comment by daniruiz** [comment]
The issue here is with the mimetype your system is using not the icons. `vnd.adobe.flash.movie` should be a movie, the icon for flash works as intended
![image](https://user-images.githubusercontent.com/12565871/95578225-d4849280-0a33-11eb-8bca-19028e8e0055.png)
