### ISSUE TITLE
COPR: enable build for CentOS 8

### ISSUE THREAD

**Issue by fepitre** [daniruiz/flat-remix#158]
I've forked your COPR repository to test build for CentOS 8 and it works. Do you mind to enable Epel for CentOS 8  please?

**Comment by fepitre** [comment]
@daniruiz any update on this?

**Comment by daniruiz** [comment]
OMG! Sorry :( I thought I had already enabled it
It's done now, sorry for the delay

**Comment by fepitre** [comment]
No problem. Thank you :)
