### ISSUE TITLE
Flatpak applications are broken when using packaged system-wide theme

### ISSUE THREAD

**Issue by egzakharovich** [daniruiz/flat-remix#161]
Fedora 33 Silverblue. Installed this theme pack from Fedora repositories and activated it using GNOME Tweaks.

Flatpak have a portal what connects host icon packs to flatpaked applications. But because of deduplication applied using absolute path symlinks, flatpaked GNOME applications throw error and exit.

```
$ flatpak run org.gnome.gedit

(gedit:2): Gtk-WARNING **: 17:16:56.232: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Произошла ошибка открытия файла /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Нет такого файла или каталога (g-io-error-quark, 1)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Произошла ошибка открытия файла /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Нет такого файла или каталога (g-io-error-quark, 1)
```

The related flatpak issue is flatpak/flatpak#2149.

There are two ways to fix it:
1. Provide `org.freedesktop.Platform.Icontheme.*` package
2. Disable deduplication in RPM spec [like paper-icon-theme did](https://bodhi.fedoraproject.org/updates/FEDORA-2019-6e40282ec8)

Probably, should do both...

Temporary workaround is to install icon theme to home folder.

**Comment by egzakharovich** [comment]
I don't know if you're the one maintaining Fedora package, but the [problem is here](https://src.fedoraproject.org/rpms/flat-remix-icon-theme/blob/master/f/flat-remix-icon-theme.spec#_48) and maybe I'll submit a PR later. Need to register on FAS first...

**Comment by daniruiz** [comment]
The theme should work with flatpak without trouble, also the theme can't improve that so that should be a different issue
I don't maintain the fedora package anyway
