### ISSUE TITLE
Purple folders, please.

### ISSUE THREAD

**Issue by EgorFlame** [daniruiz/flat-remix#164]

**Comment by KushagraKarira** [comment]
[colorFolderGenerator.sh](https://github.com/daniruiz/flat-remix/blob/master/tools/colorFolder/colorFolderGenerator.sh)
seems to be the file to generate different colors folders.

**Comment by daniruiz** [comment]
Yes, you could try using that script. I really have to improve the way folders are generated

**Comment by daniruiz** [comment]
Done, the script is now much better
You can find it inside the `color-folder` dir, with a some pregenerated color variants
