### ISSUE TITLE
Make flat-remix work with xfce 4.16 app icons

### ISSUE THREAD

**Issue by philipzae** [daniruiz/flat-remix#165]
In Xfce 4.16, the app icon names have changed to follow the freedesktop naming scheme resulting in flat-remix icons not appearing where they should.

**Comment by WMCB-Tech** [comment]
A workaround for that is to change the icons with alacarte as a temporary solution

**Comment by philipzae** [comment]
Here is a link mentioning the old and new names https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons

**Comment by daniruiz** [comment]
Thank you! the link with the info helped a lot :wink:
