### ISSUE TITLE
Doesn't work on gnome tweak tool

### ISSUE THREAD

**Issue by GAO23** [daniruiz/flat-remix#166]
Only shell theme appears, all others such as cursors and icons do not have anything when I try to set them in the tweak tool. I am using ubuntu 20.04.

**Comment by daniruiz** [comment]
Could you provide some extra information?
How did you install the theme
Which (flat-remix) themes did you install (there's flat-remix: icons, flat-remix-gtk: apps & flat-remix-gnome: shell)
