### ISSUE TITLE
Ren'Py

### ISSUE THREAD

**Issue by CavaleriOmar** [daniruiz/flat-remix#167]
App Name: Ren'Py
Icon Name: renpy
Distribution: Arch
Original Icon:
![index-logo](https://user-images.githubusercontent.com/54171779/109693427-ef45d800-7b89-11eb-90e6-700b3caa1f9d.png)

**Comment by daniruiz** [comment]
Thanks, moved to https://github.com/daniruiz/flat-remix/issues/152
