### ISSUE TITLE
Entensions (and every extensions settings) on Gnome 40

### ISSUE THREAD

**Issue by alescdb** [daniruiz/flat-remix#172]
Hi,

Very nice theme, I'm using it for a while now :-)

- ArchLinux
- Gnome 40
- flat-remix-gtk 20201129-1

Every extensions app (and individual extension settings) is starting with the wrong theme :

![Screenshot from 2021-04-24 09-23-09](https://user-images.githubusercontent.com/5646825/115951160-8884d100-a4df-11eb-9bbe-9990cb518f2e.png)

It works with Adwaita-dark :
![Screenshot from 2021-04-24 09-22-55](https://user-images.githubusercontent.com/5646825/115951149-7efb6900-a4df-11eb-8af2-f7f051dc447a.png)

**Comment by alescdb** [comment]
Wrong repo, sorry !! :(

**Comment by daniruiz** [comment]
Hi there, don't worry. The issue is due to gnome extensions being GTK4, and there's already a GTK4 theme request in the flat-remix-gtk repo :wink: 
I'll try to add GTK4 support with the next gnome release, for now I'm focused on Skeous GTK that does support GTK4
