### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by kyb3rvizsla** [daniruiz/flat-remix#178]
I would like this theme on android, it would look good with NetHunter and the same icons as its desktop version.

**Comment by Yisus7u7** [comment]
> I would like this theme on android, it would look good with NetHunter and the same icons as its desktop version.



> I would like this theme on android, it would look good with NetHunter and the same icons as its desktop version.

![Screenshot_20210730-201519](https://user-images.githubusercontent.com/64093255/127724138-fb1d3ea7-1110-4245-8412-7fda77a6c27b.png)

ReadyIt's compatible, find out first before you ask

**Comment by Yisus7u7** [comment]
@daniruiz You can close this

**Comment by kyb3rvizsla** [comment]
@Yisus7u7 but that's not android it's termux with proot-distro

**Comment by Yisus7u7** [comment]
Therefore, those catches are of termux, without proot-distro, it is x11-repo

https://wiki.termux.com/wiki/Graphical_Environment

It is an ordinary android cell phone

**Comment by Yisus7u7** [comment]
![Screenshot_20210730-210219](https://user-images.githubusercontent.com/64093255/127725439-5ee46c27-3214-486d-8924-19e0ea3beee1.png)
![Screenshot_20210730-183817](https://user-images.githubusercontent.com/64093255/127725441-96d20842-2f60-4a6f-8fc1-c1619b6ff9c2.png)

**Comment by kyb3rvizsla** [comment]
@Yisus7u7 Yes, it is compatible there because it is "linux", just as flat remix icons are compatible in raspberry, I want them in pure android.

**Comment by Yisus7u7** [comment]
You know that's impossible right? 

That can't be done, the only thing would be the icons, but it's not worth it

**Comment by kyb3rvizsla** [comment]
@Yisus7u7 it is possible and for me if it is worth it, it would be very good android

**Comment by Yisus7u7** [comment]
The icon theme yes, but the GTK theme does not, is impossible

**Comment by kyb3rvizsla** [comment]
@Yisus7u7 Yes, I refer to the Icons pack.

**Comment by daniruiz** [comment]
Sorry but I don't have the time to develop an icon theme for android
