### ISSUE TITLE
Wrong icon of weather-overcast-symbolic for OpenWeather extension

### ISSUE THREAD

**Issue by siicosmos** [daniruiz/flat-remix#180]
![Screenshot from 2021-08-10 12-12-23](https://user-images.githubusercontent.com/32992508/128921165-0b3ed95d-38ee-452a-bb24-890a16b323fb.png)

Apparently, the wrong weather icon for overcast weather has been referenced. I did a few tests and I cannot fix this on my own. The issue appears that the extension is not picking up `weather-overcast-symbolic.svg`. Instead, it picks the `weather-overcast.svg`. Other, the default yaru icon theme works fine. I checked the directory of that theme. It seems they don't carry weather icons other than symbolic ones.

BTW, the nonsymbolic weather icons are quite blurry.
![Screenshot from 2021-08-10 12-21-44](https://user-images.githubusercontent.com/32992508/128922291-bc6baa1d-2b89-434d-af9b-10f91cccb87f.png)

OS: Ubuntu 20.04 LTS
OpenWeather Extension Version: 105
Flat-Remix-Icon Version: 20210620

**Comment by daniruiz** [comment]
I think this should be fixed with the latest updates from this repository.
Anyway I can't support extensions as they could include any type of icon and makes it hard to maintain
