### ISSUE TITLE
ZST compression on PPA.

### ISSUE THREAD

**Issue by rauldipeas** [daniruiz/flat-remix#185]
I'm getting this error when installing your theme from PPA.
```
dpkg-deb: erro: o arquivo '/var/cache/apt/archives/flat-remix_20210922_all.deb' utiliza compressão desconhecida para o membro 'control.tar.zst', a desistir
```

**Comment by daniruiz** [comment]
Are you using debian? I think ubuntu patched apt to work with zstd compression and made launchpad package in that format.
But there's nothing I can really do
