### ISSUE TITLE
Installation with dnf hanging on Fedora 35

### ISSUE THREAD

**Issue by dav-is** [daniruiz/flat-remix#187]
`flat-remix-icon-theme-0.0.20211214-1.fc35.noarch.rpm` gets stuck on this forever
```
  Preparing        :                                                        1/1 
  Installing       : flat-remix-icon-theme-0.0 [========================= ] 1/3
```

I had it installed already, but the upgrade failed with something about overriding certain files? I forgot to copy the error from there...

I removed it and tried to reinstall it and now it just hangs

**Comment by dav-is** [comment]
Installing the old version doesn't seem to help. Seems something strange became corrupted?

**Comment by pizzadude** [comment]
dnf bug https://bugzilla.redhat.com/show_bug.cgi?id=2029709

as a workaround extract the rpm and manually copy the icons
