### ISSUE TITLE
The icon theme Flat-Remix-Teal-Dark apparently has missing icons

### ISSUE THREAD

**Issue by iswhy** [daniruiz/flat-remix#189]
I thought it should produce exactly the same icon set as Flat-Remix-Blue-Dark (which I can download from my Manjaro icon setting) except for the folder color, but it does not. For instance the LibreOffice icons are different from Flat-Remix-Blue-Dark.
Is it indeed that the development hasn't reached that stage or am I doing something wrong during installation?

**Comment by daniruiz** [comment]
LibreOffice uses it's own icon themes not the system one. So changing the desktop icons doesn't affect libreoffice

**Comment by iswhy** [comment]
Well, when I use Flat-Remix-Blue-Dark, LibreOffice icons do change though.
When I use Flat-Remix-Teal-Dark, LibreOffice icons do not look like that from Flat-Remix-Blue-Dark.
I am wondering wether this is intended because I thought the only difference between Flat-Remix-Blue-Dark and Flat-Remix-Teal-Dark is just the folder color.
