### ISSUE TITLE
Onboard uses application icon for panel

### ISSUE THREAD

**Issue by adrian5** [daniruiz/flat-remix#190]
When running **Onboard**, the icon in the panel is the one from `/apps/scalable/onboard.svg` which looks out of place. I think the `/panel/onboard-panel.svg` icon would be the one to use.

I'm using **Flat Remix Teal Dark** on Xfce 4.16

**Comment by daniruiz** [comment]
Onboard has a setting to change the icon to the symbolic one

**Comment by adrian5** [comment]
What setting would that be, is it exposed in the GUI? I can't seem to find it.

![onboard-config](https://user-images.githubusercontent.com/5426924/156893139-668410bf-0677-4547-8faa-ae0e621eb59e.png)

**Comment by daniruiz** [comment]
Can't find it now. I'm quite sure there was a setting before.
Anyway, that's not something I can fix from the icon theme, that's hardcoded in onboard

**Comment by adrian5** [comment]
Ok, I understand. Thanks.
