### ISSUE TITLE
All colors (Light version) link to Black

### ISSUE THREAD

**Issue by adrian5** [daniruiz/flat-remix#191]
The symlink `actions/symbolic` in Light color versions points to `Flat-Remix-Black-Dark/actions/symbolic` instead of the Dark version of its own color.

Example: [Flat-Remix-Teal-Light](https://github.com/daniruiz/flat-remix/blob/master/Flat-Remix-Teal-Light/actions/symbolic)

This creates a broken link when packaged/downloaded separately.

**Comment by daniruiz** [comment]
Thank you! I didn't see that.
Should be fixed now ;)
