### ISSUE TITLE
question about color codes -for Flat-Remix-Blue-Dark

### ISSUE THREAD

**Issue by blub4747** [daniruiz/flat-remix#197]
Hello,
Could you please tell me which  html color codes your are using for the 'Flat-Remix-Blue-Dark'.
I really like your selection and would like to use the same color's on some of my own apps.
thx,user4747

**Comment by daniruiz** [comment]
Heya! You can find an svg with the color-scheme here https://github.com/daniruiz/flat-remix/blob/master/flat-remix-palette.svg
