### ISSUE TITLE
Issue with calendar icon in Evolution

### ISSUE THREAD

**Issue by mcvittal** [daniruiz/Flat-Remix#25]
Hi! Love the icon pack, but I've got a small issue with the Calendar icon.

In Evolution, [it's massive ](https://imgur.com/Sj6H8FU). and looks terrible. Well it still looks great even zoomed that much, but I'd like it to be a bit smaller to match the other icons.

The issue doesn't occur on Adwaita icon pack so there's something wrong with the icon. If you could fix it upstream, that'd be amazing!

Keep up the good work!

**Comment by daniruiz** [comment]
I think that with the new index.theme update it might be fixed
