### ISSUE TITLE
Pantheon

### ISSUE THREAD

**Issue by lababiba** [daniruiz/Flat-Remix#27]
Can you add supporting Elementary OS 0.4 Loki (Pantheon shell) please?
When i choose your icon pack my icons become broken.
1.09 build

**Comment by lednhatkhanh** [comment]
+1 Please support pantheone too!

**Comment by daniruiz** [comment]
If I have time I will try to support pantheon but as you can understand I will be more centred in the shell I'm using (at this time gnome)

**Comment by lababiba** [comment]
I began use gnome cause of your theme)
