### ISSUE TITLE
Recent Files in Cinnamon Menu

### ISSUE THREAD

**Issue by MPE2016** [daniruiz/Flat-Remix#34]
Hi there,

First of all, many cheers to you for making this great icon theme!

I have noticed a small issue in the cinnamon main menu. The recent files icon uses a different, yellow/orange colored folder. I'm pretty sure you actually want that to be the standard blue one.

I've added a screenshot (in Dutch) to show you what I mean. Look for the words "Recente bestanden":). 

Many thanks in advance!

All the best,

MPE

![schermafdruk van 2016-12-07 08-00-57](https://cloud.githubusercontent.com/assets/15818884/20958076/ed3f5b70-bc53-11e6-9b06-d2209a1fa053.png)

**Comment by daniruiz** [comment]
Is it fixed now with the new folder icons?

**Comment by MPE2016** [comment]
seems fixed!
