### ISSUE TITLE
License question - GPL and CC

### ISSUE THREAD

**Issue by hlechner** [daniruiz/Flat-Remix#35]
Hello @daniruiz 

First congratulations for the nice iconset!

I would like to question you about the license: due to Numix project are licensed under GPLv3 you shouldn't include the GPL license together referencing the Numix icons inside your iconset?

Remember: It's just a question, I'm not an expert in the license subject

**Comment by daniruiz** [comment]
I don't really know, I've never used licenses. Is it really possible to use 2 licenses?

**Comment by hlechner** [comment]
I believe to add the second license would be hard, maybe need to specify what file is GPL3 and what is CC-BY-SA4.

I've searched for compatibility between CC-BY-SA 4 and GPL 3 I found this:


> Likewise, CC-BY-SA 4.0 explicitly permits relicensing modified versions to GNU GPL version 3, but GPL version 3 does not permit relicensing to CC-BY-SA. This issue should never arise for software code; Creative Commons says its licenses are not meant for code, and says that the license to use for code is the GNU GPL. But there are other kinds of works, such as hardware designs or game art, where you might have occasion to merge material released under CC-BY-SA with material released under the GNU GPL. This can be done through CC-BY-SA's explicit relicensing permission.

Link: https://www.gnu.org/licenses/license-compatibility.en.html

So, maybe re-license everything to GPL 3 could be a solution (if the other icons that you use from are CC-BY-SA 4 too)
