### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by TimoWilken** [daniruiz/Flat-Remix#36]
In most GTK3 applications, the symbolic icons nicely adapt to the current font colour -- see the screenshot of Nautilus below.

![nautilus](https://cloud.githubusercontent.com/assets/3159813/22027164/d9c52236-dcca-11e6-9b35-13ea6e11baa9.png)

However, in some GTK3 (e.g. GtkHash, see below), GTK2 and Qt applications, this does not work.

![gtkhash](https://cloud.githubusercontent.com/assets/3159813/22027165/db40dcf4-dcca-11e6-8b5d-a902bb7bc80b.png)

Would you consider making a version of the icons that works with dark themes in all applications?

**Comment by daniruiz** [comment]
Thank you for writing. I haven't designed the icon pack for dark themes but as soon as I have time I will solve it.
