### ISSUE TITLE
Icons missing in panel

### ISSUE THREAD

**Issue by thickset** [daniruiz/Flat-Remix#37]
Hi,
Great theme, there's just one issue though. I am using ubuntu 16.04 with unity and there are  Network, Sound and Battery icons missing from the top panel. Any idea how to fix this?

![icons](https://cloud.githubusercontent.com/assets/26323009/23789856/e5a57eea-057c-11e7-9389-7b479f92831e.png)

**Comment by daniruiz** [comment]
Thank you for writing. Now I don't have much time to solve it due to University but as soon as I can I will fix it.

**Comment by summermick** [comment]
you may close it.
I solved it on my system by install [Flat-Plat](https://github.com/nana-4/Flat-Plat)
