### ISSUE TITLE
Not Working in Ubuntu 17.04 unity

### ISSUE THREAD

**Issue by Mrprofessor** [daniruiz/Flat-Remix#39]
I tried that on my Ubuntu 17.04 unity.Not working.

**Comment by daniruiz** [comment]
At this moment I only officially support gnome-shell. Anyway Ubuntu will switch back to gnome-shell with the next release.

**Comment by daniruiz** [comment]
At this moment I only officially support gnome-shell. Anyway Ubuntu will switch back to gnome-shell with the next release.
