### ISSUE TITLE
Cinnamon Settings Applet Icon shows XFCE logo

### ISSUE THREAD

**Issue by Vencorr** [daniruiz/Flat-Remix#46]
Currently, using the latest build from this git page, the applet icon in the cinnamon system settings shows an XFCE logo.

I currently have /apps/scalable/cs-applets.svg modified to the cinnamon logo for the time being, but this would be a nice issue to have fixed.

This is its current look:
![1f3c67](https://user-images.githubusercontent.com/23224476/29760403-e82a4b2c-8b88-11e7-84d3-88891c3cb256.png)

By the way, appreciate the icon theme. Love it.

**Comment by daniruiz** [comment]
Is it fixed now?
