### ISSUE TITLE
WiFi connecting status icon missing

### ISSUE THREAD

**Issue by Jannomag** [daniruiz/Flat-Remix#47]
The icon for the WiFi connection status is missing, it shows only an ugly old school icon.
In Papirus icon theme it works correctly.

![bildschirmfoto vom 2017-09-03 11-07-59](https://user-images.githubusercontent.com/31586674/30001882-98464f1c-909b-11e7-8975-11b412872e16.png)

**Comment by daniruiz** [comment]
Is it fixed now?
