### ISSUE TITLE
Help for distro packages

### ISSUE THREAD

**Issue by daniruiz** [daniruiz/Flat-Remix#48]
How can I create a ppa or deb file so that it gets updated with newer versions, or maybe git based.
Could someone create and maintain packages for different distros?

Or otherwise where can I find the best information.

**Comment by kashm1r** [comment]
You can create a script to automate packaging with git releases.

https://github.com/pinepain/ppa-packaging

Unfortunately I can not create and test packages because I do not use a debian-based distribution.

**Comment by daniruiz** [comment]
Thanks! That helped me a lot. :+1:

**Comment by KushagraKarira** [comment]
Hi, i am working on .deb package at https://github.com/KushagraKarira/flat-remix
