### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by daniruiz** [daniruiz/flat-remix#49]
Write here all the icons that you think are missing on this theme and you would like them to be added

**Comment by pavlepiramida** [comment]
**monodevelop** and **unity-monodevelop**?


https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Monodevelop_Logo.svg/768px-Monodevelop_Logo.svg.png

and unity-monodevelop is same icon with a little unity emblem on lower right corner.

I bet you could make them prettier!

**Comment by balamurali27** [comment]
Nylas mail ? https://www.nylas.com/nylas-mail/

**Comment by uthidata** [comment]
the MATLAB icon is missing

**Comment by jeffshee** [comment]
astah* http://astah.net/
Thanks! I love your icon!

**Comment by riumutu** [comment]
Bright looking icon theme that suits Adapta GTK theme very well!

Icon for Frescobaldi is missing. It is music notation software based on Lilypond music editor.
http://www.frescobaldi.org/

The original icon is like below:
![Frescobaldi](http://frescobaldi.org/style/1/frescobaldi-icon.png "Frescobaldi")

**Comment by tomashavlas** [comment]
I'd like to get Intellij IDEA, and Android Studio icons worked in.

**Comment by kyawkyawsoezhu** [comment]
The **Wired Connected** Icon, the first one is Ubuntu 18.04 original, the second one is Flat-remix, in my opinion the original is more appropriate and already flat

![screenshot from 2018-07-23 14-29-59](https://user-images.githubusercontent.com/14541103/43064721-c38f0b6c-8e85-11e8-9a93-bce4c5375799.png)

![screenshot from 2018-07-23 14-34-43](https://user-images.githubusercontent.com/14541103/43064857-1a131fa0-8e86-11e8-9e31-17ef315f269b.png)

**Comment by tylerbartnick** [comment]
I would love for JetBrains IDE's to get some icons. This is a fantastic theme and I see the .idea folder in the project so I'm aware that the project maintainer has familiarity with the software. Ideally, I would love to see IntelliJ IDEA get some love. @daniruiz

**Comment by Dhatheway** [comment]
DragonDisk - http://www.s3-client.com/

**Comment by la55u** [comment]
qBittorrent (non-tray icon)

**Comment by Ultimator14** [comment]
IDA Pro
https://www.hex-rays.com/products/ida/index.shtml

**Comment by pavlepiramida** [comment]
TypeScript meme is missing,that would be neat to have!

**Comment by edrose** [comment]
Virtualbox Folder icon. There are icons for less used services such as OwnCloud, but not one for VirtualBox
