### ISSUE TITLE
fcitx status icons become transparent and invisible

### ISSUE THREAD

**Issue by gapplef** [daniruiz/flat-remix#50]
Latest Flat Remix on Ubuntu 17.10

How to reproduce:
1. Install `TopIcons plus` extension, the fcitx status icons will appear on the top bar(with `ubuntu appindicator` extension the fcitx status icons not appeared, might be a bug.)
2. Enable Flat-Remix icons theme and restart the shell

Result:
The fcitx status icons will become transparent and invisible, but the icon is still there.

The default Ubuntu mono or Adwaita icons have no such problems.

**Comment by daniruiz** [comment]
Couldn't reproduce the issue
