### ISSUE TITLE
Gnome Terminal - Stretched Title Icon

### ISSUE THREAD

**Issue by ziyan-junaideen** [daniruiz/flat-remix#52]
First of all thanks for the great theme. I have been using stock Ubuntu for a long time and I decided to switch to Arch on Gnome. Trying to spice things up a little I stumbled on Flat Remix. Great work guys!

Here is my issue. I am using Gnome 3.26.2. I installed the theme and the icon theme through the browser plugin. Later I installed the icon theme using the AUR (https://aur.archlinux.org/packages/super-flat-remix-icon-theme/).

The problem is that when I select Flat Remix, the terminal is having a larger than usual icon. Its bigger than its button.

![screenshot from 2017-11-05 12-30-19](https://user-images.githubusercontent.com/762159/32412674-23588308-c225-11e7-9638-597dadc1ea00.png)

I tried changing themes application themes and shell themes with no success. Changing the icon theme works, but I really like this icon theme.

Now after I installed and configured the UI, I yesterday installed KDEnlive, Inkscape and Gimp and some other setup for web development. Wonder if some thing else might have had an effect. But I doubt since changing the icon theme fixes it.

Any advice on how I can fix this would be appreciated, if this is not an bug. Thanks and wish you great.

**Comment by daniruiz** [comment]
It's a common issue in gnome-terminal. It happens with those icon themes that use scalable images rather than multiple fixed size icons, and at the moment I haven't found a nice solution.

**Comment by daniruiz** [comment]
Since GNOME 3.28 this bug is finally solved.
