### ISSUE TITLE
Request to add ChangeLog.md & TODO.md to better road map of project and be more specific 

### ISSUE THREAD

**Issue by Bonsitar** [daniruiz/Flat-Remix#58]
It would be better if you add  ChangeLog & TODO files in markdown format for a to better road map of project and be more specific.
Thanks.

**Comment by Bonsitar** [comment]
Now, [here](https://github.com/daniruiz/Flat-Remix/pulls) I created 3 new and important files (as I think at least) as pull requests to the project. I am newbie to git and GitHub so if I am doing this in a wrong way help me please.

**Comment by daniruiz** [comment]
I do not really understand why I need to add those files. The .gitignore file is not needed, the changelog.md is equivalent to the commit messages and I rather improve the theme than spend time reviewing the changes, and the TODO.md file is another file to keep updating.
I really appreciate your advice but at the moment I do not think it is necessary.

**Comment by Bonsitar** [comment]
Oh, OK!
Thanks anyway for your reply.
Good luck.
