### ISSUE TITLE
Volume floating window icon is low quality

### ISSUE THREAD

**Issue by terencode** [daniruiz/flat-remix#62]
The floating window opening when you adjust your volume settings using your keyboard in Gnome shows a low quality speaker icon.

**Comment by daniruiz** [comment]
Can you post a screenshot?

**Comment by terencode** [comment]
![peek 2018-02-19 19-38](https://user-images.githubusercontent.com/12665563/36392645-91c6b03c-15ac-11e8-9a90-dec4c973c33e.gif)

**Comment by daniruiz** [comment]
OMG! It doesn't happen in the computers I've installed the theme, so I don't know how to replicate it. Have you downloaded the lastest version?

**Comment by terencode** [comment]
@daniruiz I figured out it only happens with the light version.

**Comment by daniruiz** [comment]
I thing I've solved the problem with this commit. Please, remove completely the version you have now and try this new one.

I hope it's solved.

**Comment by terencode** [comment]
Fixed, thanks!
