### ISSUE TITLE
[Feature] Ability to choose folder icon color

### ISSUE THREAD

**Issue by terencode** [daniruiz/flat-remix#63]
Other icons themes propose that feature and I think it could be quite nice to have it on this one too.

**Comment by daniruiz** [comment]
I have just added support for folder color.

If you can, please try it and tell me if everything works correctly.

**Comment by tombertoli** [comment]
How do I change the folder colors?

**Comment by terencode** [comment]
@daniruiz Works great!
Would it be possible to add something similar to https://github.com/PapirusDevelopmentTeam/papirus-folders/blob/master/papirus-folders to change the color globally?
