### ISSUE TITLE
Chromium Browser icon seems broken ( black lines/triangles )

### ISSUE THREAD

**Issue by notzain** [daniruiz/flat-remix#64]
The Chromium icon seems broken. There appear to be black lines between each color transition. My guess is that these are supposed to be the transition shadows? 

This problem appears on main, light and dark theme.

Using Ubuntu 16.04 / KDE, on the daniruiz/flat-remix ppa.

![image](https://i.imgur.com/wbXoNpA.png)

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/36617625-7672225a-18e8-11e8-8436-26bdeda835bb.png)

I don't understand why it happens, but in all the computers I've tried the icon seems ok. Does it happen with other icons?

**Comment by notzain** [comment]
Of the apps I have installed, only Chromium has this problem. I have re-installed Flat Remix and the problem persists. The problem appeared after the Flat-Remix update.

I just booted into XFCE instead, and the icon appears normal there. Might be a bug on KDE's end?

**Comment by notzain** [comment]
Seems to be getting even weirder. Installing from either master, or release, results into missing icons. Several icons (including Chromium) , appear transparent/missing.

When the .svg is opened in an image viewer or browser, it seems to be the correct image. Is there any way I can go back to the previous version?

**Comment by konstantingoretzki** [comment]
Same problem for me with Antergos (Arch Linux) with KDE. I've installed flat-remix via the [AUR](https://aur.archlinux.org/packages/flat-remix-git/). Icons for chromium and google-chrome seem to be affected. However only the icons in the taskbar are buggy, the icons in the upper left corner of the window look fine for both.

**Comment by AGitBoy** [comment]
I'm having this problem as well, on KDE Neon. I've installed from the ppa.

**Comment by yancelawang** [comment]
Also happen to me in Arch Linux with KDE Plasma 5.13

**Comment by daniruiz** [comment]
It's solved now
