### ISSUE TITLE
vlc 3.0 fails to launch GUI with this icon theme

### ISSUE THREAD

**Issue by ghost** [daniruiz/flat-remix#72]
Under Arch Linux and xfce4, vlc 3.0 will not launch GUI if this icon pack is set as the active one. The error message looks like
```
VLC media player 3.0.2 Vetinari (revision 3.0.2-0-gd7b653cf14)
[00005566914b9570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Gdk-Message: 15:26:22.928: vlc: Fatal IO error 2 (No such file or directory) on X server :0.0.
```

The issue happens if I obtain the icon pack from github repo, as well as if I build & install the corresponding package in aur.

Originally reported at https://bugs.archlinux.org/task/57805 , and https://bbs.archlinux.org/viewtopic.php?id=235223 may also be relevant.

**Comment by Pr0gm4n** [comment]
+1

Unfortunately, I had the exact same problem on Fedora 28 installing the pack from github. Disabling flat-remix icon theme "solved" the issue for now... even though I quite liked the theme.

**Comment by Ultimator14** [comment]
Vlc is looking not only for the `vlc.svg` icon but also for `vlc.png` which is missing in the Flat Remix icon theme. As a workaround you can copy the Adwaita `/usr/share/icons/hicolor/32x32/apps/vlc.png` to `/usr/share/icons/Flat-Remix/apps/scalable/vlc.png` (I'm using gentoo so maybe the paths are a little different for you).

**Comment by aaronjensen** [comment]
Ran into the same issue with zeal. Is this a bug with Zeal/VNC or is there a way to configure fallback icons?

**Comment by aaronjensen** [comment]
This fixes it for me: `ln -s /usr/share/icons/Flat-Remix-Blue-Light/apps/scalable/zeal.{svg,png}`**
