### ISSUE TITLE
Icons show null in description

### ISSUE THREAD

**Issue by raidensub** [daniruiz/flat-remix#74]
I don't think this is a serious issue.
When i install the icon theme from the ppa in Ubuntu 18.04, there is no description for the icon theme. It just show null in the description, i am using xfce4 and the appearance program. Not a big deal i think, but a little annoying.
![screenshot_2018-06-14_11-20-58](https://user-images.githubusercontent.com/2764868/41400175-0bbeb368-6fc5-11e8-8318-96fb7513cffd.png)

**Comment by daniruiz** [comment]
I've just fixed this bug in the last commit :)
