### ISSUE TITLE
KDE file manager missing icon

### ISSUE THREAD

**Issue by now-im** [daniruiz/flat-remix#75]
In KDE there is a significant icon missing. I am providing an image to describe the problem.
![image](https://user-images.githubusercontent.com/22009014/41499426-e561c3ac-71a1-11e8-9d13-b13ebbcf6b5e.png)
Here is a similar problem to shed some light into the problem:
https://github.com/keeferrourke/la-capitaine-icon-theme/issues/335

**Comment by daniruiz** [comment]
I've just fixed this bug in the last commit :)
