### ISSUE TITLE
Request: Update Eclipse IDE Icon

### ISSUE THREAD

**Issue by btd1337** [daniruiz/flat-remix#83]
The Eclipse IDE icon does not look good.

Could you update it to be closer to the original?

![eclipse](https://user-images.githubusercontent.com/11943860/46922575-7017cf80-cfe1-11e8-845a-0cd198fb546c.png)

**Comment by daniruiz** [comment]
Sorry but I prefer mine.

![eclipse](https://user-images.githubusercontent.com/12565871/49321219-6cdf9100-f506-11e8-82f5-b7a40bba3e86.png)
