### ISSUE TITLE
Status bar volume icon shows the old one with a medium volume

### ISSUE THREAD

**Issue by terencode** [daniruiz/flat-remix#85]
* Setting the volume to a medium value shows the old icon.
* If you go over it with your mouse, it shows  the new one.

---
gnome-shell 3.30.2
ArchLinux

**Comment by josh1dev** [comment]
Sounds like a GNOME / Distro mistake and probably has nothing to do with the user shell theme / icons.

**Comment by terencode** [comment]
Can't reproduce the issue anymore. Closing...
