### ISSUE TITLE
Icon Change Request: Mime type icons for video files

### ISSUE THREAD

**Issue by yash1610** [daniruiz/flat-remix#87]
I believe that the current Mime type icon for video files looks out of place with all the other flat icons. It looks like something from the 2000s and really brings down the flat look

An icon like the one used in the Papirus Icon set would be really nice.

**Comment by daniruiz** [comment]
This one?
![image](https://user-images.githubusercontent.com/12565871/49329980-11ee7e00-f588-11e8-8fbf-9ea8059f54aa.png)
Well, a like it but I think I'm going to change it annyway for the app video icon

<img src="https://user-images.githubusercontent.com/12565871/49330001-78739c00-f588-11e8-80c7-e557417b3978.png" width=125>

**Comment by yash1610** [comment]
ya that would be really nice, maybe it can be an alternate option for people who like the other one
