### ISSUE TITLE
Battery icon shows higher battery percent.

### ISSUE THREAD

**Issue by georg3tom** [daniruiz/flat-remix#89]
The battery icon shows higher values. 
When the battery percent was around thirty battery icon shows around 60%-75%.
I'm using fedora 29.

**Comment by Keyikedalube** [comment]
I think the designer intended it that way.

I had trouble with that lasting battery status icon at first but soon I just got used to it. However, critical battery notification is still displayed, so, I think it's a design matter.

**Comment by KushagraKarira** [comment]
My battery is 37% and the icon shows it like 80%, i am changing it.

**Comment by daniruiz** [comment]
I checked this and it also happens with the default icon theme, no idea why. Flat-Remix does include multiple icons for different battery charges
