### ISSUE TITLE
Idea to add icon for view-app-grid-symbolic 

### ISSUE THREAD

**Issue by gleal17** [daniruiz/flat-remix#90]
## Description
New view-app-grid-symbolic.sgv for white screens. When you have a dock with backgroung-opacity 0, u cant see the app-grid.

## Images
App grid (default)
![captura de tela de 2018-12-10 10-52-36](https://user-images.githubusercontent.com/30850075/49733876-d596de00-fc69-11e8-93db-3c0e6e9ad7e1.png)

App grid ("hidden")
![captura de tela de 2018-12-10 10-52-29](https://user-images.githubusercontent.com/30850075/49733890-df204600-fc69-11e8-8b12-e198d1ec4ddc.png)

**Comment by daniruiz** [comment]
You are using none of my themes so I don't see why this is my issue :laughing:

**Comment by gleal17** [comment]
@daniruiz 
I have changed issue's name, take it like an idea.
I updated the prints using your Icon Theme. :stuck_out_tongue_closed_eyes:  I'm sorry for the print before.. 
Close issue if not interested... thank you .

**Comment by gleal17** [comment]
Thank you.. It's fine for me! :smiley:
