### ISSUE TITLE
Inconsistent panel icon sizes on Budgie

### ISSUE THREAD

**Issue by ffxsam** [daniruiz/flat-remix#91]
The icon sizes are not consistent on Ubuntu Budgie 18.04, nor is the spacing between icons.

![screenshot from 2018-12-18 00-58-52](https://user-images.githubusercontent.com/12532733/50137239-345ae980-0260-11e9-9664-060cb1d1f4a2.png)

**Comment by fdinardo** [comment]
I have a similar issue in gnome-shell though.
Here is what happen:

![2019-06-02_00-23](https://user-images.githubusercontent.com/7387557/58754267-b5373600-84cc-11e9-8ab7-25c56ab3fc49.png)

**Comment by fdinardo** [comment]
Update: This happen only with HiDPI display

**Comment by fdinardo** [comment]
> The icon sizes are not consistent on Ubuntu Budgie 18.04, nor is the spacing between icons.
> 
> ![screenshot from 2018-12-18 00-58-52](https://user-images.githubusercontent.com/12532733/50137239-345ae980-0260-11e9-9664-060cb1d1f4a2.png)

@ffxsam do you have a HiDPI display?

**Comment by Kazetoyuki** [comment]
> Update: This happen only with HiDPI display

Yep, using 'Display - Scale' or 'Fonts - Scaling Factor'
Some panel icon sizes are not consistent.

![Screenshot from 2019-07-10 20-18-31](https://user-images.githubusercontent.com/3736910/60968550-f20a0e80-a34f-11e9-97e8-50e954cc648d.png)

Panel icon size are same when 'Display - Scale = 100%' and 'Fonts - Scaling Factor = 1.00. But in HiDPI screen, anything are very small.

![Screenshot from 2019-07-10 20-19-43](https://user-images.githubusercontent.com/3736910/60968633-28e02480-a350-11e9-9c20-6fb231cb4835.png)

**Comment by fdinardo** [comment]
See this issue: https://github.com/daniruiz/flat-remix/issues/93

**Comment by jkelol111** [comment]
I still have the same issue. The theme was installed via the Fedora metapackage `flat-remix-theme`.

GNOME version: 3.36.4
Distribution: Fedora 32
Flat Remix version: 20200718
Display resolution: 2560x1440

![Bug image](https://i.imgur.com/NC4qG2r.png)

**Comment by daniruiz** [comment]
Sorry but I can't fix this. I can make icons that fit for all the DEs
Also the issue with gnome has nothing to do
