### ISSUE TITLE
Inconsistent icons size on hidpi screen

### ISSUE THREAD

**Issue by G-Ray** [daniruiz/flat-remix#93]
Fedora 29, with flat-remix installed from the copr repo.
Icons sizes are inconsistent in the top bar panel, on a 3200x1800 display. (scaling is set to 200%)

![icons](https://user-images.githubusercontent.com/2981774/49339535-c396b900-f633-11e8-971c-03c624ce3088.png)
![icons2](https://user-images.githubusercontent.com/2981774/49339537-c72a4000-f633-11e8-854e-45cd3f9de90e.png)

**Comment by daniruiz** [comment]
Well... Font scaling was never meant to be used over 1.2, and is just an accessibility feature. It looks fine set to x1.2.

**Comment by fdinardo** [comment]
> Well... Font scaling was never meant to be used over 1.2, and is just an accessibility feature. It looks fine set to x1.2.

I am not sure to follow... I am sorry.
If I set the scaling factor to 1.2 the font is very big! Also, the icon's factor form in the panel is still not consistent.
Bluetooth, mike, speakers and brightness icons are still too small compared to the others.

Other Icons-themes work really good even with a scaling factor set to 1.

Is there any chances someone fixes this issue?

**Comment by chenhongqiao** [comment]
Respectfully, I don't think this issue has anything to do with font scaling. GNOME Shell officially supports 200% scaling and that's the only way to use GNOME on a 4K screen. Also, I noticed that flatremix version 1.47 and before does not have this issue, as well as other icon theme such as papirus.

I really like flat-remix icon package and I hope this annoying issue could be fixed. I tried to mess with the index.theme and sometimes it works. I will try to dig a bit deeper and see if there's an easy fix.

Again, thank you for creating this awesome icon package.

**Comment by nstommel** [comment]
This problem exists on Gnome 41 in Fedora 35 using the flat-remix icon theme only when 2x scaling is used on my 4K display. Other icon themes like Papirus do not appear in inconsistent sizes in the Gnome shell. Please fix this flat-remix icon theme, it would be great if only the icon size was appropriate on HiDPI displays.
