### ISSUE TITLE
on correctly displayed icons

### ISSUE THREAD

**Issue by anton172** [daniruiz/flat-remix#95]
the icons are displayed correctly. Such programs as - mpv player, terminal Terminator.

**Comment by daniruiz** [comment]
What do you mean?

**Comment by anton172** [comment]
I do not know English and I use a translator, I meant - these program icons are not displayed correctly

**Comment by daniruiz** [comment]
I don't know where you are from but if it helps you I could speak Spanish.

About the icons not being displayed correctly, are you using KDE? Because if so it is a known issue that I am working on right now. Otherwise what desktop are you using? Could you provide some screenshots?

**Comment by anton172** [comment]
No, I'm using GNOME 3.30 (Fedora 29). I speak Russian, I'll take off the Screenshots in the evening, as it is now not at home and there is no computer nearby.

**Comment by anton172** [comment]
![2019-01-30 20-31-50](https://user-images.githubusercontent.com/47172018/52004955-28a24a00-24d1-11e9-93ed-934f115572d8.png)
![2019-01-30 20-32-12](https://user-images.githubusercontent.com/47172018/52004956-2a6c0d80-24d1-11e9-9867-4aac3e3ad145.png)

**Comment by anton172** [comment]
Icons work correctly, here is the report! Thank!
![2019-02-01 21-10-26](https://user-images.githubusercontent.com/47172018/52144548-515c4800-2667-11e9-8c77-59bc3fec17cb.png)

**Comment by daniruiz** [comment]
Yes, no problem! I'm updating all icons so I'll design a better one for openshot for next release.
