### ISSUE TITLE
Waterfox icon looks displaced

### ISSUE THREAD

**Issue by macco3k** [daniruiz/flat-remix#98]
I've noticed the waterfox icon looks as if the two parts are not correctly aligned. Attached a screenshot of how it appears if I open it in gimp.

![screenshot_20190225_181702](https://user-images.githubusercontent.com/5672785/53355603-a408e700-3929-11e9-92bb-c749011ad009.png)

**Comment by daniruiz** [comment]
Humm... I see...
Is this one better?

![waterfox](https://user-images.githubusercontent.com/12565871/53362828-54331b80-393b-11e9-99ad-37aea05deb06.png)

**Comment by macco3k** [comment]
Mh, actually I see the same thing. Could it be a problem with my linux?

![screenshot_20190226_183132](https://user-images.githubusercontent.com/5672785/53433486-c1ef4e00-39f4-11e9-8a5a-fd4a88f01e3a.png)

**Comment by daniruiz** [comment]
Noup, your linux is fine :+1: 
But I don't really understand what you mean about not being aligned, I see it fine.

**Comment by macco3k** [comment]
Yeah I've now realized that's how it's supposed to look after seeing the
new logo... don't really like it but ok :D

Op vr 22 mrt. 2019 19:54 schreef DяA <notifications@github.com>:
