### ISSUE TITLE
[noob question ] I can't set/choose the color of folders

### ISSUE THREAD

**Issue by MR-Diamond** [daniruiz/flat-remix#99]
I installed and set the Flat-Remix-Dark icons theme, with the wish to also set the colour of the folders (in particular the yellow color); the yellow folders svg files are located in /usr/share/icons/Flat-Remix-Dark/places/scalable/ directory; however in the appearance utility of my distribution (Linux Manjaro – XFCE) I can only set the blue folders: I don’t see any reference to other folder colors: how can I achieve this?
As suggested on this page I tried by using `gsettings set org.gnome.desktop.interface icon-theme Flat-Remix-GTK-Yellow-Dark` but without success.

**Comment by daniruiz** [comment]
To install the yellow folder variant you just need to copy the Flat-Remix-Yellow directory provided in this repo to your icons folder.
Then you can select it from your appearance utility.
Hope this has been been helpful 😄

**Comment by MR-Diamond** [comment]
You have been very friendly :-)
However was my fault: I had (installed from the AUR repo) an older version of flat-remix package; I updated it to r214.4178ead4-1 and now I am able to see all colors variant in the appearance preference pane.
So I close this ticket :+1:
